[package]
name = "Telegram_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.9", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
